# Generated by Django 5.0.6 on 2024-06-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamescore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameScore',
        ),
    ]
